# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kodacode < Formula
  desc "AI-powered CLI assistant with multi-provider support"
  homepage "https://github.com/sageil/kodacode"
  version "0.10.0"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sageil/kodacode/releases/download/v0.10.0/kodacode_0.10.0_darwin_amd64.tar.gz"
      sha256 "65d0264db01430f41f159646d056299b8e7b817e1a80f247598d5dee5c31946d"

      define_method(:install) do
        bin.install "kodacode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sageil/kodacode/releases/download/v0.10.0/kodacode_0.10.0_darwin_arm64.tar.gz"
      sha256 "a851323212df857bedf76e6fdbc1c996cb93c585ae3bbb0d4e1964908401aeee"

      define_method(:install) do
        bin.install "kodacode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sageil/kodacode/releases/download/v0.10.0/kodacode_0.10.0_linux_amd64.tar.gz"
      sha256 "fd20388a101e503d431b6899ad33f320e41241f4b78ce61d17a5680964bcc92a"
      define_method(:install) do
        bin.install "kodacode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sageil/kodacode/releases/download/v0.10.0/kodacode_0.10.0_linux_arm64.tar.gz"
      sha256 "05eb363205ee12f78da66d342ca346b1adace2d19cb329eb1ffa5ff3e42b1e06"
      define_method(:install) do
        bin.install "kodacode"
      end
    end
  end

  test do
    system "#{bin}/kodacode", "version"
  end
end
