# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koda < Formula
  desc "AI-powered CLI assistant with multi-provider support"
  homepage "https://github.com/sageil/koda"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sageil/koda/releases/download/v0.1.0/koda_0.1.0_darwin_amd64.tar.gz"
      sha256 "674bcd60bbfb3b8301674c5dad77f53347d8deac23b6bada122fb4f16820e46f"

      define_method(:install) do
        bin.install "koda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sageil/koda/releases/download/v0.1.0/koda_0.1.0_darwin_arm64.tar.gz"
      sha256 "52537122a4b2d72b51d81075e4c42abdc15914b8a5844b2824321abd8c99732e"

      define_method(:install) do
        bin.install "koda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sageil/koda/releases/download/v0.1.0/koda_0.1.0_linux_amd64.tar.gz"
      sha256 "dd89896f72010e7a8b886bebdee499f4b06d0cca722b79aef40081e2aded2d5c"
      define_method(:install) do
        bin.install "koda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sageil/koda/releases/download/v0.1.0/koda_0.1.0_linux_arm64.tar.gz"
      sha256 "f6a1d922ff1cfbc26d624a9b001382875ba191a58c983a25122f67f8f9179b7f"
      define_method(:install) do
        bin.install "koda"
      end
    end
  end

  test do
    system "#{bin}/koda", "version"
  end
end
