# This file was generated by GoReleaser. DO NOT EDIT.
cask "kodacode" do
  version "0.10.0"

  on_macos do
    on_intel do
      url "https://github.com/sageil/kodacode/releases/download/v#{version}/kodacode_#{version}_darwin_amd64.tar.gz"
      sha256 "9c60c7623cfdb92da5147a706cccb5e3731230ec0a1eb4b2376a69a2fce20bb9"
    end
    on_arm do
      url "https://github.com/sageil/kodacode/releases/download/v#{version}/kodacode_#{version}_darwin_arm64.tar.gz"
      sha256 "d317a25bd1a4c8afda7c73ee0e052ef7ecafa381ba580cd77072af8b87c86a54"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sageil/kodacode/releases/download/v#{version}/kodacode_#{version}_linux_amd64.tar.gz"
      sha256 "85d242407797f1d55699c9640421f455bb1228ef991da928d439381ee79727f7"
    end
    on_arm do
      url "https://github.com/sageil/kodacode/releases/download/v#{version}/kodacode_#{version}_linux_arm64.tar.gz"
      sha256 "964e9548ae91d5f4c165fa319198daf6c0aacf7cf2166943cd9536103a23ad85"
    end
  end

  name "kodacode"
  desc "AI-powered CLI assistant with multi-provider support"
  homepage "https://github.com/sageil/kodacode"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kodacode"

  # No zap stanza required

end
