# This file was generated by GoReleaser. DO NOT EDIT.
cask "kodacode" do
  postflight do
    system_command "/usr/bin/xattr",
      args: ["-dr", "com.apple.quarantine", "#{staged_path}/kodacode"]
  end

  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "569826b32293e88d86a8380bc07e24f7f62c501ff6b48212dba53b7654fc267a"
      url "https://github.com/sageil/kodacode/releases/download/v#{version}/kodacode_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "622ccc9a7d7f4450cd38aa9279399a9fa585180ac193500648b353d59782ca71"
      url "https://github.com/sageil/kodacode/releases/download/v#{version}/kodacode_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c8a58e63dad61d8ba6d729cb10d4afc9e950645e464ccf19a3e3dc6a63494051"
      url "https://github.com/sageil/kodacode/releases/download/v#{version}/kodacode_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bc2c2b52d532a419d71cf575ce387446dd1b9a155a90be94178ecf40c616bb8a"
      url "https://github.com/sageil/kodacode/releases/download/v#{version}/kodacode_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kodacode"
  desc "AI-powered CLI assistant with multi-provider support"
  homepage "https://github.com/sageil/kodacode"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kodacode"

  # No zap stanza required

end
