# This file was generated by GoReleaser. DO NOT EDIT.
cask "kodacode" do
  version "0.10.0"

  on_macos do
    on_intel do
      url "https://github.com/sageil/kodacode/releases/download/v#{version}/kodacode_#{version}_darwin_amd64.tar.gz"
      sha256 "7664cb00c333f55c03dc427f86a4fde6adb44ada1c2cf0c55776e646035202c6"
    end
    on_arm do
      url "https://github.com/sageil/kodacode/releases/download/v#{version}/kodacode_#{version}_darwin_arm64.tar.gz"
      sha256 "3ccc7c276ff16404abc48081e4536622dfaf88d8e6f0985a8f9a12a6867361cc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sageil/kodacode/releases/download/v#{version}/kodacode_#{version}_linux_amd64.tar.gz"
      sha256 "dd4da9586f1389c5fbcb89906e5904e673739e8116ccfca59991318a2f176fc8"
    end
    on_arm do
      url "https://github.com/sageil/kodacode/releases/download/v#{version}/kodacode_#{version}_linux_arm64.tar.gz"
      sha256 "dd5019ccf50aba6d2c2f2b6b65ce09b88fcd33b19c758e939815409fd719fbfe"
    end
  end

  name "kodacode"
  desc "AI-powered CLI assistant with multi-provider support"
  homepage "https://github.com/sageil/kodacode"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kodacode"

  # No zap stanza required

end
